### PR TITLE
Add new countries

### PR DESCRIPTION
**Pull request by Growthfyi**

### CODE REVIEW

**Review by thoeva — CHANGES_REQUESTED** [review]
@Growthfyi Is the Penalties section for Belgium/Denmark/Ireland correct? Looks like a copy and paste from the UK one and for example it's the [Data Protection Authority](https://www.dataprotectionauthority.be/citizen)  in charge in Belgium, not the ICO

In Ireland.md you've also referenced Denmark, I assume that's an oversight

**Review by thoeva — CHANGES_REQUESTED** [review]
` These are the Denmark Marketing Act and EU GDPR`

Do you mean the Denmark Marketing Practices Act?

**Comment by Growthfyi** [comment]
Let me double check everything.

**Comment by Growthfyi** [comment]
@thoeva here the update:

1. Yes it's Denmark Marketing Practices Act – will update that
2. Countries following GDPR (both UK and EU version) have ICO in charge of GDPR, but you are correct as countries like Belgium have 2 laws and their nation's law has a different body – will add an extra paragraph for this.

**Comment by thoeva** [comment]
@Growthfyi Yep the only country following the UK GDPR is the UK. So they have the ICO in charge, no other country outside of the UK has the ICO.
image

Denmark have the [Datatilsynet](https://www.datatilsynet.dk/)
Ireland have the DPC, [Data Protection Commission](https://www.dataprotection.ie/)

**Comment by Growthfyi** [comment]
Will fix it – thanks for highlighting

**Comment by Growthfyi** [comment]
I was actually missed the fact that some things are changed even inside EU so this was an error, will fix this.

**Comment by Growthfyi** [comment]
@thoeva changes done!

**Pull request merged**
